import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "../../context/LanguageContext";

export const metadata: Metadata = {
  title: "Que comemos hoy ?",
  description: "Generated by Que comemos hoy ?",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html lang="es">
        <body>{children}</body>
      </html>
    </LanguageProvider>
  );
}
